import time
from utils.i18n import DEMO_SUMMARY, DEMO_RISKS


def analyze_document(text: str, lang: str = "en") -> dict:
    """Return a demo analysis in the requested language. No API key required.

    Returns {"summary": str, "risks": list[str]}.
    """
    time.sleep(2)

    word_count = len(text.split())
    char_count = len(text)

    demo_notes = {
        "en": (
            f"\n\n*— Demo mode. Document was {word_count:,} words / {char_count:,} characters. "
            "In production this summary would be generated by an AI based on your actual document.*"
        ),
        "ta": (
            f"\n\n*— டெமோ பயன்முறை. ஆவணம் {word_count:,} வார்த்தைகள் / {char_count:,} எழுத்துகள். "
            "உண்மையான பயன்பாட்டில் இந்த சுருக்கம் உங்கள் ஆவணத்தின் அடிப்படையில் AI உருவாக்கும்.*"
        ),
        "hi": (
            f"\n\n*— डेमो मोड। दस्तावेज़ {word_count:,} शब्द / {char_count:,} अक्षर था। "
            "वास्तविक उपयोग में यह सारांश AI द्वारा आपके दस्तावेज़ के आधार पर बनाया जाएगा।*"
        ),
    }

    summary = DEMO_SUMMARY.get(lang, DEMO_SUMMARY["en"])
    summary += demo_notes.get(lang, demo_notes["en"])
    risks = [r.strip() for r in DEMO_RISKS.get(lang, DEMO_RISKS["en"])]

    return {"summary": summary, "risks": risks}
